version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      android: 29
  pre_build:
    on-failure: ABORT
    commands:
      - echo Pre Build started on `date`
  build:
    on-failure: ABORT
    commands:
      - ./gradlew assembleDebug
      - ./gradlew assembleDebugAndroidTest
      - ./codacy.sh
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './ExampleApplication/build/outputs/apk/debug/*.apk'
  name: 'AndroidSDK'
  discard-paths: yes