version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      android: 29
  pre_build:
    on-failure: ABORT
    commands:
      - echo Pre Build started on `date`
  build:
    on-failure: ABORT
    commands:
      - ./gradlew assembleDebug
      - ./gradlew assembleDebugAndroidTest
      - COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - ./codacy.sh $COMMIT_ID
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './ExampleApplication/apk/androidTest/debug/*.apk'
  discard-paths: yes


