version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - ./gradlew assembleDebug
      - ./gradlew assembleDebugAndroidTest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './ExampleApplication/build/outputs/apk/debug/*.apk'
  name: 'AndroidSDK'
  discard-paths: yes