version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - pwd
      - wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
      - mkdir temp
      - ls
      - mv commandlinetools-linux-6858069_latest.zip /temp
      - ls
      - cd /temp
      - pwd
      - ls
      - unzip commandlinetools-linux-6858069_latest.zip
      - export ANDROID_SDK_ROOT=`pwd`
      - pwd
      - cd /temp/cmdline-tools/bin
      - yes | ./sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
  build:
    commands:
      - pwd
      - cd ../../../
      - pwd
      - ls
      - cd /codebuild
      - ls
      - cd /output
      - ls
      - cd /src*
      - ls
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes