version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes