version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
      - mkdir temp/android
      - unzip commandlinetools-linux-6858069_latest.zip -d /temp/android
      - export ANDROID_SDK_ROOT=/temp/android
      - export PATH=$PATH:$ANDROID_SDK_ROOT
  build:
    commands:
      - ./gradlew assembleDebug --debug --stacktrace
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes