version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
  build:
    commands:
      - ./gradlew assembleDebug
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes