version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls

artifacts:
  files:
    - './AndroidSDK/build/outputs/aar/*.aar'
    - './ExampleApp/build/outputs/apk/debug/*.apk'
    - './ExampleApplication/build/outputs/apk/debug/*.apk'
  discard-paths: yes